---
abstract: 'Perl binding for asychronous hiredis API'
author:
  - 'Whitney Jackson C<< <whitney@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Which: 0
  Test::Exception: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
  XS::Object::Magic: 0.0301
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl_5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hiredis-Raw
no_index:
  directory:
    - inc
    - t
requires:
  Sub::Exporter: 0
  XS::Object::Magic: 0
  perl: 5.10.0
version: 0.01
